### ISSUE TITLE
Fedora packages considered newer than your packages

### ISSUE THREAD

**Issue by remyabel2** [negativo17/egl-wayland#1]
I recently did a distro-sync to check if there was any base packages replacing yours:

```
dnf --disablerepo=* --enablerepo=fedora-multimedia distro-sync
```
And found these:

```
    Downgrade   egl-wayland-1.1.10-4.20220806git885f0a5.fc36.i686   @fedora-multimedia
    Downgraded  egl-wayland-1.1.10-7.20220806git885f0a5.fc36.i686   @@System
    Downgrade   egl-wayland-1.1.10-4.20220806git885f0a5.fc36.x86_64 @fedora-multimedia
    Downgraded  egl-wayland-1.1.10-7.20220806git885f0a5.fc36.x86_64 @@System
    Downgrade   libavtp-0.1.0-1.fc36.x86_64                         @fedora-multimedia
    Downgraded  libavtp-0.2.0-1.fc36.x86_64                         @@System
    Downgrade   libmpeg2-0.5.1-14.fc36.x86_64                       @fedora-multimedia
    Downgraded  libmpeg2-0.5.1-24.fc36.x86_64                       @@System
    Downgrade   svt-vp9-libs-0.3.0-2.fc36.x86_64                    @fedora-multimedia
    Downgraded  svt-vp9-libs-0.3.0-7.fc36.x86_64                    @@System
    Reinstall   egl-gbm-1.1.0-2.fc36.x86_64                         @fedora-multimedia
    Reinstalled egl-gbm-1.1.0-2.fc36.x86_64                         @@System
```

I believe this is because their RPM release is 7, which obviously is considered newer than 4. `gstreamer1-plugin-libav` is affected as well. I know this affects multiple packages, but figured I'd put it in one place rather than spam multiple issues.

**Comment by scaronni** [comment]
Hi, thanks for reporting. Not a problem per se, it means the same package I need are already in Fedora and I can probably delete my copy. I will double check everything.

**Comment by remyabel2** [comment]
Thanks.

It can be a problem if someone tries to disable your repository and remove the packages, as it requires careful invocations of `dnf distro-sync --allowerasing`. For example, gnome-shell depends on some gstreamer packages, so trying to remove gstreamer from your repository will fail because gnome-shell is a protected package. I also needed to do `dnf swap`.

For context (but not entirely relevant), I was creating scripts to allow easy enabling/disabling of RPMFusion and your repos for testing purposes.

**Comment by remyabel2** [comment]
If it helps, here's a list that i grepped from my shell history:

```
sudo dnf swap libfdk-aac fdkaac --allowerasing
sudo dnf swap open264-libs mozilla-openh264 --allowerasing
sudo dnf swap gstreamer1-plugins-bad gstreamer1-plugins-bad-free --allowerasing
# This is not present in base packages, so need to remove before distro-sync
dnf remove gstreamer1-vaapi
dnf --allowerasing --disablerepo=fedora-multimedia distro-sync
```

So not that many packages overall I think. The rest can be removed with autoremove.

**Comment by scaronni** [comment]
Some updates, will be online in a few hours.

- `egl-wayland` updated for `el8`, `el9`, `fc35` and `fc36`.
  - Newer versions in `fc37`+ are fine in Fedora. But i might reintroduce it if I need a quicker fix.
- `libavtp` updated for`el7`, `el8` and `fc35`
  - Newer versions in `el9` and `fc36`+ are fine in Fedora and have been deleted from the `multimedia` repository.
- `libmpeg2` has just a better SPEC file, but the package in Fedora is fine as well.
  - I've requested admin access in Fedora so I can also build for `el7`, clean up the SPEC file and remove the package from the `multimedia` repository.
- `egl-gbm` is fine in Fedora for `fc35`+.
  - I've deleted versions from the `nvidia` and `multimedia` repositories for `fc35`+ but i might reintroduce it if I need a quicker fix.
- `gstreamer1-libav` has been renamed to `gstreamer1-plugins-libav`. I need a local copy as the FFMpeg version does not always match with Fedora.

Looking at the rest.

**Comment by scaronni** [comment]
- `svt-vp9` is fine as is in `el8+`. I just keep it in `el7`.

**Comment by scaronni** [comment]
- `svt-av1` I've retired from `fc37+`.
